### PR TITLE
Linux and ci

### PR DESCRIPTION
**Pull request by GrimSqueaker**
Fixed merge conflicts between my Linux+CI branch and the resolution upgrade branch.
Linux CI will come later.

### CODE REVIEW

**Comment by GrimSqueaker** [comment]
Update: This PR includes Linux CI now

**Comment by thobbsinteractive** [comment]
Nice. I just merged it. What did you use for CI? Did you find a Jenkins
server somewhere to run the build on? or some free service where you could
build?

**Comment by GrimSqueaker** [comment]
Thanks.
This is just GitHub actions that comes free with GitHub. They use Windows and Linux containers running on GitHub servers and I am not aware of limitations for free repositories at the moment. The configuration of the CI is located in the .github/workflows directory of the repo.

**Comment by thobbsinteractive** [comment]
I have just been reading about it. Normally companies charge something for
using cloud computing or limit its use per month, github do not seem to,
which is nice because setting up jenkins CI builds is not much fun.

Anyway nice work setting up the CI builds. yml is not my area of expertise
:)

Good night

Tim

**Comment by GrimSqueaker** [comment]
I just read that it is limited to "2,000 Actions minutes/month". A build takes about 3 minutes for Windows and Linux each. So it might make sense to limit the actions to the development and master branch instead of all feature branches. And if needed it can still be triggered manually.

**Comment by thobbsinteractive** [comment]
Hi Seb,

Yeah it makes sense to limit CI to just the dev and master branches then.
Still that's a lot for free.

I am looking a conan, but having explored the conan-center repo, there only
seems to be libpng there. SDL libraries are missing as is libogg and kiss.
- Libpng I think is used for exporting art files and so maybe it is not
essential.
- Kiss is used in the editor, so if at some point I get to separating that
into another project, I guess it will also not be an issue in the future.
- libogg is used for the ogg music, but I'd rather use the original Midi
stuff (run via SDL mixer) and later replace the music with MP3s of the
original Midi files mixed with some very nice instruments in Cubase.

But that still leaves the SDL libraries. Ironically there is a nuget.exe
for Linux. There are a lot of the libraries we need that are hosted in
nuget and with simple call to the nuget.exe we can restore all the
dependencies for both Windows and Linux platforms.
 MS now apparently have decent Linux emulation under windows (most likely
developed for there Xamarin/Android stuff), so I might try nuget with the
CMake very soon and if it works send you a pull request :)

Kind regards

Tim

**Comment by GrimSqueaker** [comment]
Hi Tim,

I will prepare a PR for the changes to CI to reduce the load and also look into Sonarcloud CI.

For Conan the conan-center is not the only source. The bincrafters have SDL: https://bintray.com/bincrafters/public-conan/sdl2%3Abincrafters
But I think for the moment we could also just go with nuget on Windows and system libraries on Linux. Because it already works and this plumbing tasks are probably not what we want to spend a lot of time on.
I've seen that you started using issues. That's great. I think it would make sense to have this all in one place - your fork. I do not know GitHub well enough if there is a better way than having multiple forks. I mean to not have this as private forks but a shared repository instead.

Cheers,
Sebastian

**Pull request merged**
